name: "Update Tag"
description: "Update the provided tag in the Github repo"
author: "Richard Simko"
inputs:
  tag_name:
    description: "Name of the tag to create or update"
    required: true

runs:
  using: "node12"
  main: "src/main.js"
branding:
  icon: "tag"
  color: "green"
